#:schema node_modules/wrangler/config-schema.json
name = "jdzh-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8ff1b983071c44f3a55c0a098e7545a3" }
]

[assets]
directory = "./public"
